services:
  postgres:
    image: postgres:15
    container_name: sirene_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - sirene_postgres_data:/var/lib/postgresql/data
    shm_size: '1g'
    command: >
      postgres
      -c shared_buffers=512MB
      -c effective_cache_size=1536MB
      -c work_mem=64MB
      -c maintenance_work_mem=256MB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c max_parallel_workers_per_gather=2

  redis:
    image: redis:7
    container_name: sirene_redis
    ports:
      - "6380:6379"
    volumes:
      - sirene_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  sirene_postgres_data:
  sirene_redis_data:
